baseurl = "/"
languageCode = "en-us"
title = "R gems and collection of erroRs"
theme = "hugo-xmin"
googleAnalytics = "UA-177852142-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "A website containing R gems I mostly found on twitter and how I fixed my own code."
    footer = "&copy; [Umair Durrani](https://durraniu.github.io) 2017 -- 2019 | [Github](https://github.com/durraniu) | [Twitter](https://twitter.com/umairdurrani87)"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
